Infrastructure: add custom TXT input file
tduretz/MDOODZ7.0 pull request #96
Opened 2023-02-17 12:10 UTC by halterw

2023-02-17 12:12 UTC, tduretz reviewed
Fine for me!

2023-02-17 12:19 UTC, kulakovri requested changes

2023-02-17 12:19 UTC, kulakovri commented on README.md
> +Specify an .txt input file from SETS folder with TXT:
To specify a .txt...

2023-02-17 12:19 UTC, kulakovri commented on README.md
> +Specify an .txt input file from SETS folder with TXT:
...folder with TXT parameter

2023-02-17 12:19 UTC, kulakovri commented on README.md
> +make build SET=RiftingChenin TXT=RiftingChenin_specific.txt
RiftingChenin_alternative.txt

2023-02-17 14:46 UTC, kulakovri reviewed
It's good, but would worth to have a second look on readme.md
@halterw you can merge it nevertheless

2023-02-17 16:33 UTC, halterw commented
Hi @kulakovri, thanks, I've applied your suggestions. Feel free to reformulate it. :) 
Also, I've noticed that in the README.md the chapter about cmake is redundant and I feel that parts of it might need some reviewing and editing.

2023-02-18 10:29 UTC, kulakovri approved these changes

2023-02-18 10:29 UTC, kulakovri commented
@halterw feel free to merge it

2023-02-20 14:44 UTC, merged